spring.application.name=store
spring.data.mongodb.uri=mongodb://localhost:27017
jwt.secret=gaurav-secret-key

# MongoDB configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=futsal_booking

# Server port
server.port=8080

# Max File Size
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
